name: ipotato_timer
description: A small timer app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  provider: ^6.0.4
  freezed_annotation: ^2.2.0
  drift: ^2.2.0
  get_it: ^7.2.0
  flutter_svg: ^1.1.6
  assets_audio_player: ^3.0.6
  path_provider: ^2.0.11
  path: ^1.8.1
  sqlite3_flutter_libs: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  drift_dev: ^2.2.0+1
  mockito: ^5.3.2
  flutter_native_splash: ^2.2.15

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  fullscreen: true

  android_12:
    image: assets/splash.png
    fullscreen: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/arrowDown.svg
    - assets/icons/isoundwave.svg
    - assets/sounds/never_gonna_give_you.mp3