name: ipotato_timer
description: A small timer app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.3
  provider: ^6.0.4
  freezed_annotation: ^2.2.0
  drift: ^2.2.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.1.1
  flutter_lints: ^2.0.1
  freezed: ^2.2.1



flutter:
  uses-material-design: true